# List of the vs code extensions
vscode:
  extensions:
    - ms-python.python
    - juanblanco.solidity

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8501
    onOpen: open-browser

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:  
  - init: npm install --save-dev
    command: npm i -g truffle
    
  - init: pip install -r requirements.txt
    command: streamlit run walkthrough_st.py
    openMode: split-right


