# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8501
    onOpen: open-preview

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: echo 'init script' # runs during prebuild
    command: echo 'start script'

  - init: npm install -g truffle
    command: echo "truffle installed"

  - init: npm install --save-dev
    command: echo "npm install done"

  - init: pip install -r requirements.txt
    command: streamlit run walkthrough_st.py
    openMode: split-right


