# Docker image
image:
  file: .gitpod.Dockerfile
# image: gitpod/workspace-full
# List of the vs code extensions
vscode:
  extensions:
    - ms-python.python
    - juanblanco.solidity
    - ms-azuretools.vscode-docker

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8501
    onOpen: open-browser

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Start Streamlit
    init: pip install -r requirements.txt
    command: streamlit run walkthrough_st.py
    openMode: split-right
