# Docker image
image:
  file: .gitpod.Dockerfile

# List of the vs code extensions
vscode:
  extensions:
    - ms-python.python
    - juanblanco.solidity
    - ms-azuretools.vscode-docker

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8501
    onOpen: open-browser

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  # - init: echo "npm already run"
  #   command: echo "npm install done"

  # - init: echo "install prereqs"
  #   command: npm install --save-dev

  # - init: echo "install truffle"
  #   command: npm install -g truffle 

  # - init: echo "install graphcli"
  #   command: npm install -g @graphprotocol/graph-cli 

  - init: pip install -r requirements.txt
    command: streamlit run walkthrough_st.py
    openMode: split-right
